### ISSUE TITLE
My project stopped building after redux-blueprint 0.3 release

### ISSUE THREAD

**Issue by pavelbely** [cchamberlain/redux-blueprint#2]
Hi,

Your library is used as a transitive dependency in my project.
And it stopped building after redux-blueprint 0.3 release.
I got this error message:
`SyntaxError: Unexpected token operator «=», expected punc «,» [./~/redux-blueprint/lib/index.js:16,0]`

That is probably due to ES6 code is released in redux-blueprint 0.3 that is not supported by node 7.1.0.

Thanks.

---------------------------------------

Environment: node 7.1.0

**Comment by cchamberlain** [comment]
Sorry about that, I'll release an update ASAP. If you could in meantime
install one of the prior versions of it (may need to install older
redux-idle-monitor as well) that should fix the issue short term.

**Comment by pavelbely** [comment]
Thanks Cole, I'll do this.

(Btw I have the same issue with some other of your libraries - localsync and redux-mux.)

**Comment by cchamberlain** [comment]
Makes sense, I just did some upgrades to all of them, fix should solve it across the board. Rolling back all the libraries should fix in the immediate but I'll try and publish something tomorrow.

**Comment by damiangreen** [comment]
I tried rolling back "redux-idle-monitor" to v 0.7 but it has a dependency of   "redux-blueprint": "*" and as I'm not in control of this child dependency I can't see a way to fix my build...

**Comment by pavelbely** [comment]
@damiangreen You CAN control nested dependencies versions using **npm-shrinkwrap.json**.

I had absolutely the same issue and here is how I resolved that.
1. Run `npm shrinkwrap` command   
It will create **npm-shrinkwrap.json** file.
2. In  **npm-shrinkwrap.json** find **redux-blueprint** dependency
and edit it as below (specify older version)
```
"redux-blueprint": {
      "version": "0.2.23",
      "from": "redux-blueprint@0.2.23"
    } 
```
3. Delete `node_modules` library
4. Run `npm install` command
It will install dependencies specified in **npm-shrinkwrap.json**

Now the build should be fine!

**Comment by cchamberlain** [comment]
@damiangreen @pavelbely **UPDATE**: skip down to latest comment [here](https://github.com/noderaider/redux-blueprint/issues/2#issuecomment-345813666).


If you rollback `redux-idle-monitor` to the older version, and take explicit dependencies on the older packages, it will use the older ones.

Kill your `node_modules` folder then run one of the following depending on your client:

`npm install -E redux-idle-monitor@0.7.0 localsync@1.4.0 redux-blueprint@0.2.23 redux-mux@0.1.15`

OR

`yarn add -E redux-idle-monitor@0.7.0 localsync@1.4.0 redux-blueprint@0.2.23 redux-mux@0.1.15`

Sorry again for the issues, I'll try and get a fix out soon.

**Comment by cchamberlain** [comment]
@damiangreen @pavelbely I think I've fixed the issue by swapping the target to ES5. I've published new versions of everything under the `next` tag.

Instead of the last command, can you try running:

```
npm install -E redux-idle-monitor@next
```

OR

```
yarn add -E redux-idle-monitor@next
```

Ensure you have no explicit dependencies on `localsync`, `redux-blueprint`, or `redux-mux` first.

Please let me know if this fixes your issues, if so I'll bump these all up to `latest` and delete the last comment to not lead others down the wrong path.

**Comment by damiangreen** [comment]
thanks
 for your swift feedback. I'll try this first thing in the morning.

**Comment by damiangreen** [comment]
I commented on the other library, the error i'm getting is 
`ERROR in ./~/redux-mux/lib/index.js
Module not found: Error: Cannot resolve module 'tslib' in C:\damian\frontend\node_modules\redux-mux\lib`

I tried the shrinkwrap fallback option but `antd` had unmet peerdependencies so didn't work. For now I've run `npm i -S tslib` just so i can start my day. i'll have to revert once fixed. Hope this helps

**Comment by cchamberlain** [comment]
@damiangreen - thanks looking into it. I need to get myself an example setup to find some of these issues quicker (used to use these at work before I switched jobs).

**Comment by damiangreen** [comment]
sure, maybe i can even lend a hand. I'll need to understand if tsslib should be an included dependency

**Comment by cchamberlain** [comment]
@damiangreen - yes it should be a full dependency. I've released new versions if you want to give them a test that would be great. Posted instructions on https://github.com/noderaider/redux-idle-monitor/issues/20 and going to close this out as dupe, please follow up on that issue.
